sqlserver_profile:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-R6DB6Q13
      port: 1433
      database: dbtcore
      schema: dbo
      windows_login: True
      trust_cert: true